src/Entity/ReponseMessage.php
<?php

namespace App\Entity;

use App\Repository\ReponseMessageRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReponseMessageRepository::class)
 */
class ReponseMessage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\OneToOne(targetEntity=MessageContact::class, mappedBy="idReponseContact", cascade={"persist", "remove"})
     */
    private $messageContact;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_message_contact;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMessageContact(): ?MessageContact
    {
        return $this->messageContact;
    }

    public function setMessageContact(?MessageContact $messageContact): self
    {
        // unset the owning side of the relation if necessary
        if ($messageContact === null && $this->messageContact !== null) {
            $this->messageContact->setIdReponseContact(null);
        }

        // set the owning side of the relation if necessary
        if ($messageContact !== null && $messageContact->getIdReponseContact() !== $this) {
            $messageContact->setIdReponseContact($this);
        }

        $this->messageContact = $messageContact;

        return $this;
    }

    public function getIdMessageContact(): ?int
    {
        return $this->id_message_contact;
    }

    public function setIdMessageContact(int $id_message_contact): self
    {
        $this->id_message_contact = $id_message_contact;

        return $this;
    }
}

src/Controller/VentesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Horaires;
use App\Entity\Voitures;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class VentesController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager=$entityManager;
    }

    /**
     * @Route("/ventes", name="ventes")
     */
    public function index(Request $request): Response
    {
         $voituretries=null;
         $post=null;
         $prixMinimun=null;
         $prixMaximun=null;
         $kmparcouruMin=null;
         $kmparcouruMax=null;
         $annecirculationmin=null;
         $annecirculationmax=null;
         $notification=null;




        $horaires=$this->entityManager->getRepository(Horaires::class)->findAll();
        $voituresventes=$this->entityManager->getRepository(Voitures::class)->findAll();
        //dd($voituresventes);

        if ($request->isMethod('POST')) 
          {
                  
            
              
                  $prixMinimun= $request->get('prixmin'); 
                  $prixMaximun= $request->get('prixMax'); 
                  $kmparcouruMin= $request->get('kmparcouruMin'); 
                  $kmparcouruMax= $request->get('kmparcouruMax'); 
                  $annecirculationmin= $request->get('annecirculationmin'); 
                  $annecirculationmax= $request->get('annecirculationmax'); 
                  $post='definit';


                  if(empty($prixMinimun) AND empty($prixMaximun))
                  {
                      $notification='Veuillez renseigner obligatoirement une fourchette de prix minimun et maximun';
                  }
                  else
                  {
                      $voituretries=$this->entityManager->getRepository(Voitures::class)->rechercher($prixMinimun,  $prixMaximun, $kmparcouruMin, $kmparcouruMax, $annecirculationmin, $annecirculationmax);
                  }
                

                 
                 
                 
                 
          }

        
        return $this->render('ventes/index.html.twig', [
            'controller_name' => 'VentesController',
            'horaires'=>$horaires,
            'voituresventes'=>$voituresventes,
            'post'=>$post,
            'voituretries'=>$voituretries,
             'prixMinimun'=>$prixMinimun,
             'prixMaximun'=>$prixMaximun,
             'kmparcouruMin'=>$kmparcouruMin,
             'kmparcouruMax'=>$kmparcouruMax,
             'annecirculationmax'=>$annecirculationmax,
             'annecirculationmin'=>$annecirculationmin,
             'notification'=>$notification
        ]);
    }
}

templates/ventes/index.html.twig
{% extends 'base.html.twig' %}

 {% block content %}
 
  <div id="form_vente">
  
        <section>
                        <form action="#" method="post">
                            
                                            <div class="form_vente_contenu">
                                            
                                                            <div class="form_vente_content">
                                                                <label for="" class="form-label">Fourchette de prix * (min)</label>
                                                                <input type="number" name="prixmin"  {% if prixMinimun is defined %} value="{{prixMinimun}}" {% endif %}   class="form-control">
                                                            </div>

                                                            <div class="form_vente_content">
                                                                <label for="" class="form-label">Fourchette de prix * (max) </label>
                                                                <input type="number" name="prixMax" {% if prixMaximun is defined %} value="{{prixMaximun}}" {% endif %} class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                                            </div>

                                                            <div class="form_vente_content">
                                                                <label for="" class="form-label">km parcouru (min)</label>
                                                                <input type="number" name="kmparcouruMin" {% if kmparcouruMin is defined %} value="{{kmparcouruMin}}" {% endif %} class="form-control" id="exampleInputPassword1">
                                                            </div>

                                                            <div class="form_vente_content">
                                                                <label for="" class="form-label">km parcouru (max) </label>
                                                                <input type="number" name="kmparcouruMax"  {% if kmparcouruMax is defined %} value="{{kmparcouruMax}}" {% endif %} class="form-control" id="exampleInputPassword1">
                                                            </div>

                                                            <div class="form_vente_content">
                                                            <label class="form-label" for="">Année de circulation (min)</label>
                                                            <input type="number" name="annecirculationmin" {% if annecirculationmin is defined %} value="{{annecirculationmin}}" {% endif %} class="form-control" id="exampleCheck1">
                                                        </div>

                                                            <div class="form_vente_content">
                                                            <label class="form-label" for="">Année de circulation (max)</label>
                                                            <input type="number" name="annecirculationmax" {% if annecirculationmax is defined %} value="{{annecirculationmax}}" {% endif %} class="form-control" id="exampleCheck1">
                                                        </div>
                                                    
                                            </div>
                                            
                                            <div class="form_vente_contenu">
                                            <button type="submit" class="btn btn-primary">Soumettre</button>
                                            </div>
                            
                            </form>
                                        {% if notification %}
                                        <div class="alert alert-info">{{notification}}</div>
                                        {% endif %}
            </section>


   </div>


          <section>
                        <div id="article_vente_contenu">  

                                        {% if post is not null %} 

                                                {% for voituretrie in voituretries  %}
                                                    <div class="article_vente_content">
                                                    Prix: {{voituretrie.prix}} Euros<br/><img class="img_service" src="/garageParrot/public/upload/{{voituretrie.image1}}" alt=""><br/>{{voituretrie.nom}}<br/>Année: {{voituretrie.anneecirculation}}<br/>Diesel<br/>{{voituretrie.kilometrage}}km<br/><br/><a href="{{path('ventes_details',{'id':voituretrie.id})}}">Détails</a>
                                                    </div>
                                                {% endfor %}           
                                        
                                        
                                        {% else %}
                                        
                                                {% for voituresvente in voituresventes  %}
                                                    <div class="article_vente_content">
                                                    Prix: {{voituresvente.prix}} Euros<br/><img class="img_service" src="/garageParrot/public/upload/{{voituresvente.image1}}" alt=""><br/>{{voituresvente.nom}}<br/>Année: {{voituresvente.anneecirculation}}<br/>Diesel<br/>{{voituresvente.kilometrage}}km<br/><br/><a href="{{path('ventes_details',{'id':voituresvente.id})}}">Détails</a>
                                                    </div>
                                                {% endfor %}
                                        
                                        {% endif %}
                        
                         </div>
          </section>
          


          

{% endblock %}

templates/ventes/ventes_details.html.twig
{% extends 'base.html.twig' %}

 {% block content %}


    <div id="contenu_1">

                                    <div class="contenant_1">
                                        TABLEAU CARACTERISTIQUE<br/><br/>                              
                                        Nom Marque et modèle : {{voiture.nom}}<br/><br/>
                                        Année de fabrication : {{voiture.anneecirculation}}<br/><br/>
                                        Type de carrosserie : {{voiture.carrosserie}}<br/><br/>
                                        Moteur : {{voiture.moteur}}<br/><br/>
                                        Transmission : {{voiture.transmission}}<br/><br/>
                                        Kilométrage : {{voiture.kilometrage}} <br/><br/>
                                        Prix : {{voiture.prix}} <br/><br/>
                                        Contact : {{voiture.contact}} <br/><br/>
                                    </div>


                                    <div class="contenant_1">
                                            GALLERIE
                                            <div class="content_1">
                                                            <div class="content_2">
                                                                    <div class="img_galerie_1">
                                                                        <img class="img_service" src="/garageParrot/public/upload/{{voiture.image1}}" alt="">
                                                                    </div>
                                                                    <div class="img_galerie_2">
                                                                         <img class="img_service" src="/garageParrot/public/upload/{{voiture.image2}}" alt="">
                                                                    </div>
                                                            </div>

                                                            <div class="content_2">
                                                                    <div class="img_galerie_3">
                                                                        <img class="img_service" src="/garageParrot/public/upload/{{voiture.image3}}" alt="">
                                                                    </div>
                                                                    <div class="img_galerie_4">
                                                                         <img class="img_service" src="/garageParrot/public/upload/{{voiture.image4}}" alt="">
                                                                    </div>
                                                           </div>
                                            </div>
                                </div>       
         </div>

        <div id="forum_discussion">

                   {% if notification %}
                   <div class="alert alert-info">{{notification}}</div>
                   {% endif %}

                   <div class="">
                       FORMULAIRE DE CONTACT
                   </div>

                 

                   <div class="">
                         {{form(form)}}
                   </div>
<!--
                   <div class=" message_couleur">
                    Nom: Arthur Prenom: Vange<br/>    
                    MESSAGE LECTEUR
                   </div>

                   <div class=" message_couleur">
                    Nom: Arthur Prenom: Vange<br/>    
                    MESSAGE LECTEUR
                   </div>

                   <div class=" message_couleur">
                    Nom: Arthur Prenom: Vange<br/>    
                    MESSAGE LECTEUR
                   </div>
-->
                   
        </div>





 {% endblock %}